// <auto-generated />
namespace BoxService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedflavorprofilefieldtofoodboxes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedflavorprofilefieldtofoodboxes));
        
        string IMigrationMetadata.Id
        {
            get { return "201606052313167_added flavorprofile field to foodboxes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
